#!/usr/bin/env python3
"""Query FINDINGS.md the way bib.py queries the catalogue.

    .venv/bin/python scripts/findings.py                      # index table
    .venv/bin/python scripts/findings.py --status current
    .venv/bin/python scripts/findings.py --method kober
    .venv/bin/python scripts/findings.py --assumption A-002   # entries that cite it
    .venv/bin/python scripts/findings.py --cites F-019        # entries that mention it
    .venv/bin/python scripts/findings.py --show F-022         # print one entry
    .venv/bin/python scripts/findings.py --write-index        # refresh the index in FINDINGS.md
    .venv/bin/python scripts/findings.py --check-claims       # claims.md cites only current entries?

Parses the entry headings (``## F-nnn · date · title``), the ``Status:`` and
``Protocol:`` lines, and every ``A-nnn`` and ``F-nnn`` reference in the body. The method
is inferred from the protocol line: "restoration", "matching" or "etymological" (the
etymological method), "Kober". The index is written between the two marker comments in
FINDINGS.md and is the only generated text in that file; everything else is hand-written.
"""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
FINDINGS = ROOT / "FINDINGS.md"
HEAD = re.compile(r"^## (F-\d{3}) · ([0-9/\-]+) · (.+)$")
START, END = "<!-- index:start -->", "<!-- index:end -->"


@dataclass
class Entry:
    id: str
    date: str
    title: str
    status: str = ""
    protocol: str = ""
    method: str = ""
    assumptions: list[str] = field(default_factory=list)
    refs: list[str] = field(default_factory=list)
    body: str = ""


def parse(text: str) -> list[Entry]:
    entries: list[Entry] = []
    cur: Entry | None = None
    lines: list[str] = []
    for line in text.splitlines():
        m = HEAD.match(line)
        if m:
            if cur:
                cur.body = "\n".join(lines).strip()
                entries.append(cur)
            cur = Entry(m.group(1), m.group(2), m.group(3).strip())
            lines = []
        elif cur:
            lines.append(line)
    if cur:
        cur.body = "\n".join(lines).strip()
        entries.append(cur)
    for e in entries:
        s = re.search(r"Status: \*\*([^*]+)\*\*", e.body)
        e.status = s.group(1).strip() if s else "?"
        p = re.search(r"Protocols?: ([^\n]+?)(?:\. Status|\n)", e.body)
        e.protocol = p.group(1).strip() if p else "?"
        low = e.protocol.lower()
        if "kober" in low:
            e.method = "kober"
        elif "restoration" in low:
            e.method = "restoration"
        elif "matching" in low or "etymological" in low or "measurement" in low:
            e.method = "etymological"
        else:
            e.method = "other"
        e.assumptions = sorted(set(re.findall(r"\bA-\d{3}\b", e.body)), key=lambda a: int(a[2:]))
        e.refs = sorted({r for r in re.findall(r"\bF-\d{3}\b", e.body) if r != e.id}, key=lambda a: int(a[2:]))
    return entries


def expand_ranges(body: str) -> set[str]:
    """A-033 to A-041 style ranges count as citing every number in between."""
    out = set(re.findall(r"\bA-\d{3}\b", body))
    for a, b in re.findall(r"\bA-(\d{3}) to A-(\d{3})\b", body):
        out.update(f"A-{n:03d}" for n in range(int(a), int(b) + 1))
    return out


def index_table(entries: list[Entry]) -> str:
    rows = ["| id | date | method | status | title |", "|---|---|---|---|---|"]
    for e in entries:
        rows.append(f"| {e.id} | {e.date} | {e.method} | {e.status} | {e.title} |")
    return "\n".join(rows)


def write_index(text: str, entries: list[Entry]) -> str:
    block = f"{START}\n{index_table(entries)}\n{END}"
    if START in text and END in text:
        pre = text[: text.index(START)]
        post = text[text.index(END) + len(END):]
        return pre + block + post
    marker = "\n---\n"
    i = text.index(marker)
    return text[:i] + "\n## Index\n\nGenerated by `scripts/findings.py --write-index`; do not edit by hand.\n\n" + block + "\n" + text[i:]


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--status")
    ap.add_argument("--method", choices=["restoration", "etymological", "kober", "other"])
    ap.add_argument("--assumption", help="A-nnn: entries whose body cites it (ranges expanded)")
    ap.add_argument("--cites", help="F-nnn: entries that mention it")
    ap.add_argument("--show", help="F-nnn: print the entry")
    ap.add_argument("--write-index", action="store_true")
    ap.add_argument("--check-claims", action="store_true",
                    help="list F-nnn cited in docs/ai_context/claims.md that are missing or not current")
    args = ap.parse_args()

    text = FINDINGS.read_text()
    entries = parse(text)
    if args.check_claims:
        claims = (ROOT / "docs" / "ai_context" / "claims.md").read_text()
        by_id = {e.id: e for e in entries}
        cited = sorted(set(re.findall(r"\bF-\d{3}\b", claims)), key=lambda a: int(a[2:]))
        bad = 0
        for c in cited:
            e = by_id.get(c)
            if e is None:
                print(f"{c}: cited in claims.md but no such entry"); bad += 1
            elif not e.status.startswith("current"):
                print(f"{c}: cited in claims.md, status is '{e.status}'"); bad += 1
        print(f"{len(cited)} entries cited, {bad} not current or missing")
        sys.exit(1 if bad else 0)
    if args.write_index:
        FINDINGS.write_text(write_index(text, entries))
        print(f"index written: {len(entries)} entries")
        return
    if args.show:
        for e in entries:
            if e.id == args.show:
                print(f"## {e.id} · {e.date} · {e.title}\n\n{e.body}")
                return
        sys.exit(f"no entry {args.show}")
    sel = entries
    if args.status:
        sel = [e for e in sel if args.status.lower() in e.status.lower()]
    if args.method:
        sel = [e for e in sel if e.method == args.method]
    if args.assumption:
        sel = [e for e in sel if args.assumption in expand_ranges(e.body)]
    if args.cites:
        sel = [e for e in sel if args.cites in e.refs]
    print(index_table(sel))
    print(f"\n{len(sel)} of {len(entries)} entries")


if __name__ == "__main__":
    main()
